[[inputs.mqtt_consumer]]
  servers = ["tcp://192.168.5.1:1883"]
  topics = ["/sensor/#"]
  data_format = "json"
  tag_keys = ["name"]

[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database = "sensors"
  skip_database_creation = false